Исправление опечатки в конспекте 3 лекции
MPSU/APS pull request #40
Opened 2024-01-13 20:09 UTC by tyrty23

2024-01-13 20:35 UTC, tyrty23 commented
Также небольшие синтаксические ошибки в 15 лекции

2024-01-13 21:44 UTC, tyrty23 commented
Также исправление пути файла из за чего не отображалась картинка

2024-01-14 10:15 UTC, HepoH3 requested changes
К правкам лекций 14-15 вопросов нет.

2024-01-14 10:15 UTC, HepoH3 commented on .pic/Lectures/03. Digital arithmetics/fig_08.png
Нужно не добавить новую пикчу, а заменить седьмую. Та ссылка на вторую пикчу была ошибочной, предполагалось указывать не седьмую пикчу, где была формула. Но твоя лучше.
Поэтому необходимо заменить седьмую пикчу твоей, и исправить ссылку со второй пикчи на седьмую.

2024-01-14 10:15 UTC, HepoH3 commented on Lectures/03. Digital arithmetics.md
> +Другой подход к построению АЛУ предполагает выведения оптимальных выражений, в которых конкретные значения управляющих сигналов преобразуют выражение так, чтобы оно выполняло требуемую операцию. В ра
```suggestion
Другой подход к построению АЛУ предполагает выведения оптимальных выражений, в которых конкретные значения управляющих сигналов преобразуют выражение так, чтобы оно выполняло требуемую операцию. В рассмотренном примере поддерживается 48 операций (но некоторые повторяются):

- 32 арифметических:
  - 16 операций когда M=1, P<sub>i-1</sub>=0;
  - 16 операций когда M=1, P<sub>i-1</sub>=1;
- 16 логических, когда M=0 (от P<sub>i-1</sub> ничего не зависит).
```

2024-01-14 10:15 UTC, HepoH3 commented on Lectures/03. Digital arithmetics.md
> +![../.pic/Lectures/03.%20Digital%20arithmetics/fig_02.png](../.pic/Lectures/03.%20Digital%20arithmetics/fig_08.png)
```suggestion
![../.pic/Lectures/03.%20Digital%20arithmetics/fig_02.png](../.pic/Lectures/03.%20Digital%20arithmetics/fig_07.png)
```

2024-01-14 10:30 UTC, HepoH3 approved these changes

2024-01-14 10:31 UTC, merged

2024-01-14 10:31 UTC, HepoH3 commented
Напиши в телегу группу и фамилию, чтоб я проставил баллы